### ISSUE TITLE
Track version 1.2.0

### ISSUE THREAD

**Issue by David-Desmaisons** [NeutroniumCore/Neutronium#52]
Global roadmap can be found here: https://trello.com/b/1q0TNsWv/neutronium

* Neutronium.Core
  - [ ] Support of complex javascript deserialization when used as command argument (Today only basic types and object converted from C# are supported)- prototype
* Neutronium.JavascriptFramework.Vue 

  - [ ] Updates to last version of the framework and tools

**Comment by David-Desmaisons** [comment]
Done:


Version 1.2.0

* Neutronium.Core
  - [x] Better export of commands to .cjson format
* Neutronium.JavascriptFramework.Vue 
  - [x] Updates to last version of the framework and tools
* Neutronium.WebEngine.ChromiumFx
  - [x] Support of x84 and x64 bit builds

**Comment by David-Desmaisons** [comment]
Done:

Version 1.3.0
* Neutronium.Core
  - [x] Allow hot-reload for locally served files (issue #62 )
  - [x] Expose API to save object as CJSON (issue #63  )
  - [x] Improve export to CJSON of char and DateTime value
* Neutronium.WebEngine.ChromiumFx
  - [x] Allow areo-snap on chromeless window
* Neutronium.JavascriptFramework.Vue
  - [x] Update to vue devtools v4.0.0

**Comment by David-Desmaisons** [comment]
Done:

Version 1.3.1
* Neutronium.JavascriptFramework.Mobx
  - [X] Prototype mobx framework adapter.

**Comment by David-Desmaisons** [comment]
Version 1.5.0

* Neutronium.WPF
- [x] Provide improved user experience on live-reload (add option to live on right click)

-NeutroniumCfx
- [x] Improve support of pack url.

**Comment by David-Desmaisons** [comment]
Version 1.5.2

* [x]  Fix for issue #103 and issue #105 ( PR #106 )
* [x]  Reactivity for custom command on contextual menu PR #98
* [x]  Opening external url in browser PR #97
* [x]  Improved stability when using hot-reload

**Comment by David-Desmaisons** [comment]
version 1.6.0
* Neutronium.WebEngine.ChromiumFx
  - [x] Updates to last version of CEF (Chromium 77)
* Neutronium.JavascriptFramework.Vue
  - [x] Update to vue version 2.6.11
  - [x] Update to last devtools version
